
.PHONY:FORCE

prepare:FORCE

# 自动生成 *_FORCE目标
%_FORCE:FORCE
	target=$@;\
	target=$${target%_FORCE};\
	[[ -f $$target ]] && rm  $$target;\
	$(MAKE) $$target

open_terminal:
	cygstart /usr/bin/mintty
    
dump_elf:
	aarch64-elf-objdump -D output.elf|less
dump_binary:
	aarch64-elf-objdump -D -b binary -m aarch64 output.bin|less
	
# 辅助检查
aux_check/1/2/3/4/%.o:% src/shared/empty.o
	mkdir -p $$(dirname $@) && cp src/shared/empty.o $@
	
include ../makefile.IMAGES.targets
